### ISSUE TITLE
csrf token is not written in token

### ISSUE THREAD

**Issue by sjquant** [NovemberOscar/Sanic-JWT-Extended#27]
## Problem

This library supports csrf protection when using cookies. There's csrf-read part in tokens.py and decorators.py. But, when I looked into source code, I couldn't find csrf-write part, and its' impossible to write csrf in `create_access_token` and `create_refresh_token` functions.

## Proposed Solution

It would be solved if we can add csrf claims when encoding jwt.

**Comment by sjquant** [comment]
I sent a PR in #28

**Comment by sjquant** [comment]
@NovemberOscar Could you see my PR please?

**Comment by rscarrera27** [comment]
Sorry for late response 🙏 I'm trying to review this by this weekend

**Comment by sjquant** [comment]
@NovemberOscar Thank you 👍

**Comment by sjquant** [comment]
I'll close this issue because PR has been merged.
