### ISSUE TITLE
Get unexpected keyword argument 'token' while using decorator in class

### ISSUE THREAD

**Issue by krishnajangid** [NovemberOscar/Sanic-JWT-Extended#31]
While using decorators in class-based we get an error.

TypeError: post() got an unexpected keyword argument 'token'

```python
class RestView(HTTPMethodView):
    decorators = [jwt_required()]

    async def post(self, request):
        self.__request_data = request.json
        print("POST API")
        return {}

app.add_route(Test.as_view(), '/test')
```

And another thing is while initializing role for a user it takes only one role.
```python
access_token = JWT.create_access_token(identity=username, role='staff')
```
Actually it should take a list of roles.
```python
access_token = JWT.create_access_token(identity=username, role=['staff', 'admin'])
```

**Comment by rscarrera27** [comment]
You must specify `token` parameter in your handler methods. 

https://sanic-jwt-extended.seonghyeon.dev/usage/basic.html#protect-views

**Comment by rscarrera27** [comment]
And taking a list of roles is not designed behavior. 🤔 I have to take a look for this. and I want to keep the built-in function as simple as possible, so if you want a complex access control, you may have to make your own code that interacts with JWT object.

**Comment by krishnajangid** [comment]
Thanks, @NovemberOscar.  The token issue is resolved.
