### ISSUE TITLE
jwt_required decorator only works for function view not class view

### ISSUE THREAD

**Issue by sjquant** [NovemberOscar/Sanic-JWT-Extended#4]
**Problem**

sanic_jwt_extend.jwt_required only works for function view.
It does not work for class based view like HTTPMethodView.

**Expected Behavior**

it should work for HTTPMethodView. It contains request object in the second args

**Proposed Solution**

I created _get_request function, which checks the type of args and get request object.

I pull requested it, but if you don't like it, feel free to change it.

**Comment by rscarrera27** [comment]
Thanks :)
