### ISSUE TITLE
ModuleNotFoundError when installing with requirements.txt

### ISSUE THREAD

**Issue by sjquant** [NovemberOscar/Sanic-JWT-Extended#6]
**Issue**
This module has dependency on sanic, jwt, etc. But, when i installing this package with `requirements.txt` (which has `sanic` in it) in clean virtual environment with no packages, it raises ModuleNotFoundError (sanic, and jwt either). 

**Proposed Solution**
I think it's because  `__version__` import part in setup.py. When importing `__version__`, it also tries `JWT Manager` (which imports `sanic` and `jwt`). I came up with two solutions.

1. writes versions directly in requirements.txt
2. read `__version__` with f.read() like [sanic](https://github.com/huge-success/sanic/blob/master/setup.py) I also uploaded picture of that part that part in `Sanic` below.

![image](https://user-images.githubusercontent.com/16596777/60380438-8f2b9400-9a80-11e9-9eb2-40d686b9f98e.png)

**Comment by sjquant** [comment]
@NovemberOscar

**Comment by rscarrera27** [comment]
Thanks for report :)


Can you fix and PR? I think you can fix this.


Unfortuenatly if you can't, I'll fix this by tomorrow. 😗

**Comment by sjquant** [comment]
@NovemberOscar 
Okay. I sent PR #7
